language: r
sudo: false
cache: packages
pandoc_version: 1.19.2.1

warnings_are_errors: false
r_check_args: --no-manual
r_build_args: --no-manual

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

branches:
  only:
  - master
  - develop
  
matrix:
  include:
    - r: release
      before_install:
        - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
        - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        - Rscript -e 'remotes::install_github(c("delta-rho/datadr","delta-rho/trelliscope","EMSL-Computing/MetaCycData"))'
      before_deploy: 
        - Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
      after_success:
        - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'remotes::install_cran("covr");covr::codecov()'
    - r: oldrel
      before_install:
        - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
        - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        - Rscript -e 'remotes::install_github(c("delta-rho/datadr","delta-rho/trelliscope","EMSL-Computing/MetaCycData"))'
    - r: 3.4
      before_install:
        - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
        - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        - Rscript -e 'remotes::install_github(c("delta-rho/datadr","delta-rho/trelliscope","EMSL-Computing/MetaCycData"))'
    - r: devel
      before_install:
        - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
        - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        - Rscript -e 'remotes::install_github(c("delta-rho/datadr","delta-rho/trelliscope","EMSL-Computing/MetaCycData"))'
  allow_failures:
    - r: devel
  fast_finish: true
